# Generated by Django 5.0.6 on 2024-05-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='main_stack',
        ),
    ]
